name: dicoding_flutter_fundamental
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.3.0
  provider: ^6.1.2
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  cupertino_icons: ^1.0.2
  expandable_text: ^2.3.0
  sqflite: ^2.4.2
  shimmer: ^3.0.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/img/
    - assets/lottie/
  fonts:
    - family: "Plus Jakarta Sans"
      fonts:
        - asset: assets/font/plus_jakarta_sans_bold.ttf
          weight: 700
        - asset: assets/font/plus_jakarta_sans_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/font/plus_jakarta_sans_extra_bold.ttf
          weight: 800
        - asset: assets/font/plus_jakarta_sans_italic.ttf
          style: italic
        - asset: assets/font/plus_jakarta_sans_light.ttf
          weight: 300
        - asset: assets/font/plus_jakarta_sans_medium.ttf
          weight: 500
        - asset: assets/font/plus_jakarta_sans_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/font/plus_jakarta_sans_regular.ttf
          weight: 400
        - asset: assets/font/plus_jakarta_sans_semi_bold.ttf
          weight: 600
        - asset: assets/font/plus_jakarta_sans_semi_bold_italic.ttf
          weight: 600
          style: italic
